name: Unplug
options:
  bundleIdPrefix: io.unplug
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "12.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    ENABLE_PREVIEWS: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: W959GMH66H

targets:
  Unplug:
    type: application
    platform: iOS
    sources:
      - path: Unplug
        excludes:
          - "Preview Content"
      - path: Unplug/Preview Content
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app
        INFOPLIST_FILE: Unplug/Info.plist
        CODE_SIGN_ENTITLEMENTS: Unplug/Unplug.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - target: DeviceActivityMonitor
      - target: ShieldConfiguration
      - target: UnplugWidget
    scheme:
      testTargets:
        - UnplugTests
      gatherCoverageData: true

  UnplugTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: UnplugTests
    dependencies:
      - target: Unplug
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app.tests
        GENERATE_INFOPLIST_FILE: YES

  UnplugUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UnplugUITests
    dependencies:
      - target: Unplug
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Unplug

  DeviceActivityMonitor:
    type: app-extension
    platform: iOS
    sources:
      - path: DeviceActivityMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app.device-activity-monitor
        CODE_SIGN_ENTITLEMENTS: DeviceActivityMonitor/DeviceActivityMonitor.entitlements
        INFOPLIST_FILE: DeviceActivityMonitor/Info.plist
        SKIP_INSTALL: YES

  ShieldConfiguration:
    type: app-extension
    platform: iOS
    sources:
      - path: ShieldConfiguration
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app.shield-configuration
        CODE_SIGN_ENTITLEMENTS: ShieldConfiguration/ShieldConfiguration.entitlements
        INFOPLIST_FILE: ShieldConfiguration/Info.plist
        SKIP_INSTALL: YES

  UnplugWidget:
    type: extensionkit-extension
    platform: iOS
    sources:
      - path: UnplugWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.unplug.app.widget
        CODE_SIGN_ENTITLEMENTS: UnplugWidget/UnplugWidget.entitlements
        INFOPLIST_FILE: UnplugWidget/Info.plist
        SKIP_INSTALL: YES

schemes:
  Unplug:
    build:
      targets:
        Unplug: all
        DeviceActivityMonitor: all
        ShieldConfiguration: all
        UnplugWidget: all
    run:
      config: Debug
      executable: Unplug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: UnplugTests
          parallelizable: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
